// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Ew3XduuWF1OTmdDio2vefRQjK8bcaeo',
    appId: '1:110493406334:web:f49e393dc5ea09f322342f',
    messagingSenderId: '110493406334',
    projectId: 'photozone-93b48',
    authDomain: 'photozone-93b48.firebaseapp.com',
    storageBucket: 'photozone-93b48.appspot.com',
    measurementId: 'G-NCTV0DVRBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwO_DkkD0SneIsZCtPfYYaQF8bJsaw0mY',
    appId: '1:110493406334:android:07cf6e71366b394022342f',
    messagingSenderId: '110493406334',
    projectId: 'photozone-93b48',
    storageBucket: 'photozone-93b48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANUsXvst_FPaS5pnzLa0q32jgXDUAaOfk',
    appId: '1:110493406334:ios:53b759d5e58d329522342f',
    messagingSenderId: '110493406334',
    projectId: 'photozone-93b48',
    storageBucket: 'photozone-93b48.appspot.com',
    iosBundleId: 'com.example.photoZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANUsXvst_FPaS5pnzLa0q32jgXDUAaOfk',
    appId: '1:110493406334:ios:ec9001ad6163442e22342f',
    messagingSenderId: '110493406334',
    projectId: 'photozone-93b48',
    storageBucket: 'photozone-93b48.appspot.com',
    iosBundleId: 'com.example.photoZone.RunnerTests',
  );
}
